version: 2
sphinx:
    configuration: doc/conf.py
    builder: html

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
      python: "3.10"
  
    
formats: []
python:
    install:
        - method: pip
          path: .
        - requirements: doc/requirements.txt

# if present, this section is used and python section ignored before sphinx is built
#conda:
#    environment: environment.yml
